  image: node:latest
  stages:
    - production
    
  production:
    type: deploy
    tags:
      - test
    stage: production
    image: node:latest
    script:
      - npm i
      - echo 'hellword'
    only:
      - master