version: "3"
services:
  app:
    container_name: heroku_api
    restart: always
    build: ./
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    links:
      - mongo
    networks:
      paultest:
        aliases:
          - app
  mongo:
    container_name: heroku_api_mongo
    image: mongo
    networks:
      paultest:
        aliases:
          - mongo
    ports:
      - "27017:27017"

networks:
  paultest:
    external: true
