version: 2.1
jobs:
    build:
      docker: 
        - image: circleci/node:10.3.0 # the primary container, where your job's commands are run
      steps:
        - checkout # check out the code in the project directory
        - run: echo "npm install" # run the `echo` command
        - run: npm i